/**
*	ANIMA(c) COPYRIGHT (c) 2025 CHAOS. ALL RIGHTS RESERVED.
*
*	CONFIDENTIAL INFORMATION OF CHAOS. NOT FOR DISCLOSURE OR DISTRIBUTION
*	WITHOUT CHAOS' PRIOR WRITTEN CONSENT. THIS SOFTWARE CONTAINS CODE, TECHNIQUES AND KNOW-HOW
*	WHICH IS CONFIDENTIAL AND PROPRIETARY TO CHAOS.
*
*	ANIMA(c) IS A REGISTERED TRADEMARKS OF CHAOS IN THE USA, EU AND/OR OTHER COUNTRIES.
*	ALL OTHER BRAND NAMES, PRODUCT NAMES OR TRADEMARKS BELONG TO THEIR RESPECTIVE HOLDERS.
*/

#pragma once
#include "DynamicRHI.h"

#include "RHI.h"

namespace Anima {
	bool IsRHIUsingD3D11(FDynamicRHI *RHI);
	bool IsRHIUsingD3D12(FDynamicRHI *RHI);
	bool DoesDeviceMatchGPUD3D11RHI(FDynamicRHI *RHI, int GPUIndex);
	bool DoesDeviceMatchGPUD3D12RHI(FDynamicRHI *RHI, int GPUIndex);
};
